import requests
from bs4 import BeautifulSoup
import streamlit as st


def get_song_title(url):
    """
    Retrieves the song title from the <title> tag in the HTML page.

    :param url: URL of the page containing the song
    :return: Title of the song or "suno_song" if not found
    """
    try:
        response = requests.get(url)
        if response.status_code == 200:
            soup = BeautifulSoup(response.text, 'html.parser')
            title_tag = soup.find('title')
            if title_tag:
                title = title_tag.text.strip()
                # Clean the title to extract only the song name
                title = title.split(" by ")[0]  # Remove " by @username | Suno"
                return title
        return "suno_song"
    except Exception as e:
        st.error(f"Error while retrieving the title: {e}")
        return "suno_song"


def download_audio_file(audio_url, output_path):
    """
    Downloads an audio file from a URL.

    :param audio_url: Direct link to the audio file
    :param output_path: Path and name of the output file
    :return: Path of the downloaded file
    """
    try:
        response = requests.get(audio_url, stream=True)
        if response.status_code == 200:
            with open(output_path, 'wb') as file:
                for chunk in response.iter_content(chunk_size=1024):
                    file.write(chunk)
            return output_path
        else:
            st.error(f"Failed to download, status code: {response.status_code}")
            return None
    except Exception as e:
        st.error(f"Error while downloading: {e}")
        return None


# Streamlit application
st.set_page_config(page_title="Suno Downloader", layout="centered")

# Main title
st.title("Suno Downloader")
st.write("A simple application to download public sounds from Suno. "
         "It allows you to get the sounds you like with a personalized title!")

# User inputs
url = st.text_input("Enter the Suno sound URL:",
                    placeholder="https://suno.com/song/fc991b95-e4e9-4c8f-87e8-e5e4560755e7")
custom_title = st.text_input("Enter a custom title (optional):", placeholder="Custom title")

# Button to start downloading the sound in memory
if st.button("Fetch the sound"):
    if url:
        # Get the song title from the URL
        song_title = get_song_title(url)

        # Use a custom title if provided
        if custom_title.strip():
            song_title = custom_title.strip()

        # Clean the title for the file name
        song_title = song_title.replace(" ", "_").replace("/", "_")
        audio_url = f"https://cdn1.suno.ai/{url.split('/')[-1]}.mp3"

        # Download the file
        with st.spinner("Fetching in progress..."):
            downloaded_file = download_audio_file(audio_url, f"{song_title}.mp3")

        # Check if the file was successfully fetched
        if downloaded_file:
            st.success(f"Sound successfully fetched: {downloaded_file}")
            # Allow the user to download the file
            with open(downloaded_file, "rb") as file:
                st.download_button(
                    label="Download the sound",
                    data=file,
                    file_name=f"{song_title}.mp3",
                    mime="audio/mpeg"
                )
    else:
        st.error("Please enter a valid URL.")

# Load the image
image_path = "images/tuto_lien.png"  # Replace with the path to your image

# Main page
st.markdown("""
# **How to retrieve the URL of the sound from Suno**

To download a public sound from **Suno** using this application, here’s how to retrieve the URL of the sound:

### 1. **Go to the audio player**
- Go to the page of the sound you want to download on **Suno**.
- You will see an audio player similar to the one shown below:
""")

# Display the image
st.image(image_path, caption="Example of the Suno player with the share icon highlighted.", use_column_width=True)

st.markdown("""
### 2. **Click on the share icon**
- In the player, find the **share** icon highlighted in red in the image above.
- Click on it to copy the link to the sound.

### 3. **Use the URL in the application**
- Paste this URL into the appropriate field in this application. It will look something like:  
  `https://suno.com/song/[unique_song_code]`.
- You can then download the audio file.

---

### **Important Note:**
The link generated by the share icon ensures that the application retrieves the correct audio file. Make sure to copy a valid URL to avoid errors.
""")
